/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** A Cypher duration: calendar months and days are kept apart from clock seconds. */
export declare class Duration {
  readonly months: number
  readonly days: number
  readonly seconds: number
  constructor(months?: number | undefined | null, days?: number | undefined | null, seconds?: number | undefined | null)
  /** ISO-8601 (`P1Y2M3DT4S`); zero parts are omitted and a zero duration is `PT0S`. */
  toString(): string
  toJSON(): { months: number; days: number; seconds: number }
}

/** A graph opened by [`open`]. */
export declare class Graph {
  /** Run a read-only Cypher statement. A mutating statement rejects with `InvalidArgument`. */
  executeRead(cypher: string, params?: Params | null, options?: QueryOptions): Promise<QueryResult>
  /** Run a Cypher statement that may write, as one auto-committed transaction. */
  executeWrite(cypher: string, params?: Params | null, options?: QueryOptions): Promise<QueryResult>
  /** Write a checkpoint (folding the write-ahead log) unless nothing changed since this handle's last one. */
  checkpoint(): Promise<void>
  /** Flush the write-ahead log to stable storage (the power-safe point at durability `normal`). */
  sync(): Promise<void>
  /** Checkpoint if there are unsaved changes (writable graphs), release the writer lease and close the graph. Idempotent. */
  close(): Promise<void>
  /** The path this graph was opened at. */
  get path(): string
  /** The durability level in force (`off` on a `readOnly` graph; an inherited level degrades to `off` on a disk graph). */
  get durability(): 'full' | 'normal' | 'off'
  /** Whether the graph was opened with `readOnly: true`. */
  get readOnly(): boolean
  /** Whether `close()` has completed. */
  get closed(): boolean
  /** Notices from opening the graph (a quarantined or repaired write-ahead log, a degraded durability level, a storage conversion). */
  get openWarnings(): Array<string>
}

/**
 * Forces a parameter to the engine's float type. A plain JS `1` is an integer
 * because JavaScript cannot tell `1` from `1.0`.
 */
export declare class KgFloat {
  readonly value: number
  constructor(value: number)
  toJSON(): number
}

/** A calendar date without a time or zone. */
export declare class LocalDate {
  readonly year: number
  readonly month: number
  readonly day: number
  constructor(year: number, month: number, day: number)
  /** ISO-8601 `YYYY-MM-DD`. */
  toString(): string
  toJSON(): string
}

/** A calendar date with a wall-clock time (nanosecond precision), no zone. */
export declare class LocalDateTime {
  readonly year: number
  readonly month: number
  readonly day: number
  readonly hour: number
  readonly minute: number
  readonly second: number
  readonly nanosecond: number
  constructor(year: number, month: number, day: number, hour?: number | undefined | null, minute?: number | undefined | null, second?: number | undefined | null, nanosecond?: number | undefined | null)
  /** ISO-8601 with the shortest of 0, 3, 6 or 9 fractional digits. */
  toString(): string
  /** A JS `Date` reading this wall clock as UTC; sub-millisecond digits are dropped. */
  toDate(): Date
  toJSON(): string
}

/** A WGS-84 point. */
export declare class Point {
  readonly latitude: number
  readonly longitude: number
  constructor(latitude: number, longitude: number)
  /** WKT, `POINT(longitude latitude)`. */
  toString(): string
  toJSON(): { latitude: number; longitude: number }
}

/** The `Error` every rejection carries. */
export interface KgliteError {
  /**
   * Engine error code (`CypherSyntax`, `CypherTimeout`, `ConstraintViolation`,
   * `TransactionConflict`, ...) or a binding code: `Internal`, `QueueFull`,
   * `WriterLeaseHeld`, `Closed`, `ReadOnly`, `NotDurable`.
   */
  code: string
  /** Always `"KgliteError"`. */
  name: string
  message: string
  /** Present on `WriterLeaseHeld`. */
  holder?: LeaseHolderInfo
}

/** A node as returned in a row. */
export interface KgNode {
  id: number
  labels: Array<string>
  properties: Record<string, KgValue>
}

/** A path as returned in a row. */
export interface KgPath {
  nodes: Array<KgNode>
  relationships: Array<KgRelationship>
}

/** A relationship as returned in a row. */
export interface KgRelationship {
  id: number
  type: string
  startId: number
  endId: number
  properties: Record<string, KgValue>
}

/**
 * Any value a query can return.
 *
 * `Int64` is `number` when exact and `bigint` beyond 2^53 - 1 (`integers: 'bigint'`
 * makes every integer a `bigint`). Dates, datetimes, durations and points are the
 * exported classes; nodes, relationships and paths are plain objects.
 *
 * `JSON.stringify` throws on a `bigint` (a JavaScript rule, not a kglite one): pass a
 * replacer, or define `BigInt.prototype.toJSON`, when a result may hold one.
 */
export type KgValue = null | boolean | number | bigint | string | LocalDate | LocalDateTime | Duration | Point | KgNode | KgRelationship | KgPath | Array<KgValue> | Record<string, KgValue>

/**
 * Who holds a writer lease. `pid`, `since` and `label` are what the holder published
 * (null when it had not yet, or an older build wrote the record); `self` is true when
 * the holder is this very process, i.e. a handle that was opened and never closed.
 */
export interface LeaseHolderInfo {
  pid?: number
  since?: string
  label?: string
  self: boolean
}

export interface MutationStats {
  nodesCreated: number
  relationshipsCreated: number
  propertiesSet: number
  nodesDeleted: number
  relationshipsDeleted: number
  propertiesRemoved: number
  indexesAdded: number
  indexesRemoved: number
  constraintsAdded: number
  constraintsRemoved: number
}

/** Open (or create) the graph at `path`. */
export declare function open(path: string, options?: OpenOptions): Promise<Graph>

export interface OpenOptions {
  /** Default `'full'`. Refused for `storage: 'disk'` when set explicitly. */
  durability?: 'full' | 'normal' | 'off'
  storage?: 'memory' | 'mapped' | 'disk'
  /**
   * Load the last checkpoint and take no lease; writes reject `ReadOnly`. Not
   * combinable with `durability`, `storage` or `lockTimeoutMs`.
   */
  readOnly?: boolean
  /** How long to wait for another writer to release the path. Default 0 (fail fast). */
  lockTimeoutMs?: number
  /** Per-query default; `0` disables the deadline. Default 180000. */
  timeoutMs?: number
  /** Per-query default cap on returned rows. */
  rowLimit?: number
  /** `'safe'` (default): `number` when exact, `bigint` otherwise. `'bigint'`: always `bigint`. */
  integers?: 'safe' | 'bigint'
}

/** Named parameters, referenced in Cypher as `$name`. */
export type Params = Record<string, ParamValue>

/**
 * A value accepted as a query parameter.
 *
 * A `number` that is a safe integer is sent as an integer, any other as a float
 * (use `KgFloat` to force a float); a `bigint` outside the signed 64-bit range
 * rejects. `Date` is sent as a UTC datetime. `undefined` map entries are omitted.
 */
export type ParamValue = KgValue | KgFloat | Date

export interface QueryOptions {
  /** Deadline in milliseconds; `0` disables it. */
  timeoutMs?: number
  /** Cap on rows returned; the rest are dropped and `truncated` says how many. */
  rowLimit?: number
  /** Work budget (not a row cap); exceeding it fails the query. */
  maxWorkUnits?: number
}

export interface QueryResult {
  columns: Array<string>
  /** One object per row, keyed by column name. */
  rows: Array<Record<string, KgValue>>
  /** Present for statements that write. */
  stats?: MutationStats
  /** Advisory warnings for this query; never printed. */
  warnings: Array<string>
  /** Present only when `rowLimit` dropped rows. */
  truncated?: Truncated
}

export interface Truncated {
  rowLimit: number
  totalRows: number
}

/** Engine version, equal to the workspace package version. */
export declare function version(): string
