/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface KgMap {
  [key: string]: KgValue
}

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** A Cypher duration: calendar months and days are kept apart from clock seconds. */
export declare class Duration {
  readonly months: number
  readonly days: number
  readonly seconds: number
  constructor(months?: number | undefined | null, days?: number | undefined | null, seconds?: number | undefined | null)
  /** ISO-8601 (`P1Y2M3DT4S`); zero parts are omitted and a zero duration is `PT0S`. */
  toString(): string
  toJSON(): { months: number; days: number; seconds: number }
}

/** A graph opened by [`open`]. */
export declare class Graph {
  /** Write a consistent single-file copy of the graph to `dest` while writers keep committing. */
  backup(dest: string): Promise<BackupReport>
  /** Declare (or replace) the graph's ontology and enforce it on every later write. */
  declareOntology(ontology: object | string): Promise<OntologyDeclared>
  /** Remove the graph's declared ontology. */
  clearOntology(): Promise<void>
  /** Use a JavaScript function as the graph's text embedder, for `text_score()` with a string query, `db.embeddings.embed` and `db.embeddings.query({text})`. Replaces any earlier embedder; not persisted. */
  setEmbedder(name: string, embed: (texts: string[]) => Promise<ArrayLike<number>[]> | ArrayLike<number>[], options?: EmbedderOptions): void
  /** Remove the registered embedder. With `name`, only when it is the one registered. Returns whether one was removed. */
  clearEmbedder(name?: string | undefined | null): boolean
  /** Run a read-only Cypher statement. A mutating statement rejects with `InvalidArgument`. */
  executeRead(cypher: string, params?: Params | null, options?: QueryOptions): Promise<QueryResult>
  /** Run a Cypher statement that may write, as one auto-committed transaction. */
  executeWrite(cypher: string, params?: Params | null, options?: QueryOptions): Promise<QueryResult>
  /** Stream a read-only query as an async iterator of row objects, converted a batch per event-loop turn. */
  stream(cypher: string, params?: Params | null, options?: StreamOptions): AsyncIterableIterator<KgMap>
  /** Write a checkpoint (folding the write-ahead log) unless nothing changed since this handle's last one. */
  checkpoint(): Promise<Checkpoint>
  /** Flush the write-ahead log to stable storage (the power-safe point at durability `normal`). */
  sync(): Promise<void>
  /** Checkpoint if there are unsaved changes (writable graphs), release the writer lease and close the graph. Idempotent. */
  close(): Promise<void>
  /** The path this graph was opened at. */
  get path(): string
  /** The durability level in force (`off` on a `readOnly` graph; an inherited level degrades to `off` on a disk graph). */
  get durability(): 'full' | 'normal' | 'off'
  /** Whether the graph was opened with `readOnly: true`. */
  get readOnly(): boolean
  /** Whether `close()` has completed. */
  get closed(): boolean
  /** What the open reported: the storage mode and durability in force, any degradation or conversion, and the advisories (a quarantined or saved write-ahead log) an operator should read. */
  get openInfo(): OpenInfo
  /** Start a transaction on a snapshot of the graph. Always settle it with `commit()` or `rollback()`; `transaction(fn)` does so for you. */
  begin(options?: { readOnly?: boolean }): Promise<Transaction>
  /** Run `callback` in a transaction: commit when its promise resolves, roll back when it throws. With `retries`, a lost optimistic race re-runs the callback on a fresh transaction. */
  transaction<T>(callback: (tx: Transaction) => Promise<T> | T, options?: { retries?: number, readOnly?: boolean }): Promise<T>
}

/**
 * Forces a parameter to the engine's float type. A plain JS `1` is an integer
 * because JavaScript cannot tell `1` from `1.0`.
 */
export declare class KgFloat {
  readonly value: number
  constructor(value: number)
  toJSON(): number
}

/** A calendar date without a time or zone. */
export declare class LocalDate {
  readonly year: number
  readonly month: number
  readonly day: number
  constructor(year: number, month: number, day: number)
  /** ISO-8601 `YYYY-MM-DD`. */
  toString(): string
  toJSON(): string
}

/** A calendar date with a wall-clock time (nanosecond precision), no zone. */
export declare class LocalDateTime {
  readonly year: number
  readonly month: number
  readonly day: number
  readonly hour: number
  readonly minute: number
  readonly second: number
  readonly nanosecond: number
  constructor(year: number, month: number, day: number, hour?: number | undefined | null, minute?: number | undefined | null, second?: number | undefined | null, nanosecond?: number | undefined | null)
  /** ISO-8601 with the shortest of 0, 3, 6 or 9 fractional digits. */
  toString(): string
  /** A JS `Date` reading this wall clock as UTC; sub-millisecond digits are dropped. */
  toDate(): Date
  toJSON(): string
}

/** A WGS-84 point. */
export declare class Point {
  readonly latitude: number
  readonly longitude: number
  constructor(latitude: number, longitude: number)
  /** WKT, `POINT(longitude latitude)`. */
  toString(): string
  toJSON(): { latitude: number; longitude: number }
}

/** The async iterator `Graph.stream` returns. */
export declare class RowStream {
  next(): Promise<IteratorResult<KgMap, undefined>>
  return(): Promise<IteratorResult<KgMap, undefined>>
}

/** An open transaction, from `graph.begin()` or passed to the `graph.transaction()` callback. */
export declare class Transaction {
  /** Run a Cypher statement inside the transaction. */
  run(cypher: string, params?: Params | null, options?: QueryOptions): Promise<QueryResult>
  /** Publish the transaction's writes. Rejects `TransactionConflict` (retriable) when another writer committed first. */
  commit(): Promise<void>
  /** Discard the transaction. Idempotent, and a no-op once it is committed or its graph is closed. */
  rollback(): Promise<void>
  /** Whether the transaction was opened with `readOnly: true`. */
  get readOnly(): boolean
  /** Whether the transaction is over: committed, rolled back, or abandoned by `close()`. */
  get finished(): boolean
}

/** What `backup` captured. */
export interface BackupReport {
  /** The destination file. */
  path: string
  /** Size of the published file. */
  bytes: number
  nodes: number
  relationships: number
  /** The graph's in-memory commit count at the snapshot. */
  graphVersion: number
  /**
   * Newest write-ahead-log position the file contains (`null` without a log). `number`
   * when exact, `bigint` beyond 2^53 - 1 (always `bigint` with `integers: 'bigint'`).
   */
  lsn: number | bigint | null
  /** How long writers were held off to fix the point in time. */
  lockHoldMs: number
  /** The whole call. */
  elapsedMs: number
  /** The snapshot needed a private copy first (costs a fork of the graph). */
  preparedCopy: boolean
}

/** What `checkpoint` did. */
export interface Checkpoint {
  /** `false` when nothing changed since this handle's last checkpoint, so no file was written. */
  written: boolean
  /**
   * The graph version the checkpoint covers. `number` when exact, `bigint` beyond 2^53 - 1
   * (always `bigint` with `integers: 'bigint'`).
   */
  version: number | bigint
}

export interface EmbedderOptions {
  /** Vector width. Omitted: learned from the first vector the function returns (one probe call when a statement needs it up front). */
  dimension?: number
  /** Model identity stamped on stored embeddings; default is the registration name. */
  modelId?: string
  /** How long one call may wait for the function before it fails. Default 120000. */
  timeoutMs?: number
}

/** The `Error` every rejection carries. */
export interface KgliteError {
  /**
   * Engine error code (`CypherSyntax`, `CypherTimeout`, `ConstraintViolation`,
   * `TransactionConflict`, ...) or a binding code: `Internal`, `QueueFull`,
   * `WriterLeaseHeld`, `Closed`, `ReadOnly`, `NotDurable`, `TransactionClosed`.
   */
  code: string
  /** Always `"KgliteError"`. */
  name: string
  message: string
  /** Present on `WriterLeaseHeld`. */
  holder?: LeaseHolderInfo
  /**
   * Present on `OntologyViolation`: the rule that fired (`required_property`,
   * `property_type`, `closed_labels`, `domain`, `range`). For a refused
   * declaration, the first report entry's.
   */
  rule?: string
  /** Present on `OntologyViolation`. */
  entity?: 'node' | 'relationship'
  /** Present on `OntologyViolation`: the label or relationship type. */
  entityType?: string
  /** Present on `OntologyViolation`: the offending property, `null` for a rule that has none. */
  property?: string | null
  /** Present on `OntologyViolation`: the per-rule breakdown of a refused declaration; empty for a refused write. */
  report?: Array<OntologyReportEntry>
}

/** A node as returned in a row. */
export interface KgNode {
  id: number
  labels: Array<string>
  properties: Record<string, KgValue>
}

/** A path as returned in a row. */
export interface KgPath {
  nodes: Array<KgNode>
  relationships: Array<KgRelationship>
}

/** A relationship as returned in a row. */
export interface KgRelationship {
  id: number
  type: string
  startId: number
  endId: number
  properties: Record<string, KgValue>
}

/**
 * Any value a query can return.
 *
 * `Int64` is `number` when exact and `bigint` beyond 2^53 - 1 (`integers: 'bigint'`
 * makes every integer a `bigint`). Dates, datetimes, durations and points are the
 * exported classes; nodes, relationships and paths are plain objects.
 *
 * `JSON.stringify` throws on a `bigint` (a JavaScript rule, not a kglite one): pass a
 * replacer, or define `BigInt.prototype.toJSON`, when a result may hold one.
 */
export type KgValue = null | boolean | number | bigint | string | LocalDate | LocalDateTime | Duration | Point | KgNode | KgRelationship | KgPath | Array<KgValue> | KgMap

/**
 * Who holds a writer lease. `pid`, `since` and `label` are what the holder published
 * (null when it had not yet, or an older build wrote the record); `self` is true when
 * the holder is this very process, i.e. a handle that was opened and never closed.
 */
export interface LeaseHolderInfo {
  pid?: number
  since?: string
  label?: string
  self: boolean
}

export interface MutationStats {
  nodesCreated: number
  relationshipsCreated: number
  propertiesSet: number
  nodesDeleted: number
  relationshipsDeleted: number
  propertiesRemoved: number
  indexesAdded: number
  indexesRemoved: number
  constraintsAdded: number
  constraintsRemoved: number
}

/** What `declareOntology` returns. */
export interface OntologyDeclared {
  /** `warn`-level findings of the declaration over the stored data; empty when there are none. */
  warnings: Array<string>
}

/** One line of a refused declaration's report: `count` stored entities already break `rule`. */
export interface OntologyReportEntry {
  rule: string
  entity: 'node' | 'relationship'
  entityType: string
  property?: string | null
  count: number
}

/** Open (or create) the graph at `path`. */
export declare function open(path: string, options?: OpenOptions): Promise<Graph>

/** One notice from opening a graph, such as a quarantined write-ahead log or a saved torn tail. */
export interface OpenAdvisory {
  /** Stable machine-readable kind, such as `wal_quarantined`. */
  code: string
  message: string
  /** The node or relationship types, or files, the notice concerns; empty when none. */
  affected: Array<string>
}

/** What `open` reports about the graph it returned. */
export interface OpenInfo {
  path: string
  readOnly: boolean
  /** The open created the graph. */
  created: boolean
  /** The storage mode now running. */
  storage: 'memory' | 'mapped' | 'disk'
  /** The durability level in force. */
  durability: 'full' | 'normal' | 'off'
  /** The level that was requested but degraded to `off` (a disk graph has no log). Absent otherwise. */
  degradedFrom?: 'full' | 'normal'
  /** The mode the graph was in before an explicit `storage` converted it. Absent otherwise. */
  convertedFrom?: 'memory' | 'mapped' | 'disk'
  /** Notices an operator should read; empty when the open was clean. */
  advisories: Array<OpenAdvisory>
}

export interface OpenOptions {
  /** Default `'full'`. Refused for `storage: 'disk'` when set explicitly. */
  durability?: 'full' | 'normal' | 'off'
  storage?: 'memory' | 'mapped' | 'disk'
  /**
   * Load the last checkpoint and take no lease; writes reject `ReadOnly`. Not
   * combinable with `durability`, `storage` or `lockTimeoutMs`.
   */
  readOnly?: boolean
  /** How long to wait for another writer to release the path. Default 0 (fail fast). */
  lockTimeoutMs?: number
  /** Per-query default; `0` disables the deadline. Default 180000. */
  timeoutMs?: number
  /** Per-query default cap on returned rows. */
  rowLimit?: number
  /** `'safe'` (default): `number` when exact, `bigint` otherwise. `'bigint'`: always `bigint`. */
  integers?: 'safe' | 'bigint'
  /** Which instant an unprefixed statement reads on a graph with declared validity intervals: `'today'` (default), `'all'` (no valid-time filtering) or a fixed `'YYYY-MM-DD'` day. Runtime only; not saved with the graph. */
  validTimeDefault?: string
}

/** Named parameters, referenced in Cypher as `$name`. */
export type Params = Record<string, ParamValue>

/**
 * A value accepted as a query parameter.
 *
 * A `number` that is a safe integer is sent as an integer, any other as a float
 * (use `KgFloat` to force a float); a `bigint` outside the signed 64-bit range
 * rejects. `Date` is sent as a UTC datetime. `undefined` map entries are omitted.
 */
export type ParamValue = KgValue | KgFloat | Date

export interface QueryOptions {
  /** Deadline in milliseconds; `0` disables it. */
  timeoutMs?: number
  /** Cap on rows returned; the rest are dropped and `truncated` says how many. */
  rowLimit?: number
  /** Work budget (not a row cap); exceeding it fails the query. */
  maxWorkUnits?: number
  /** Cancels the call when aborted: rejects `Cancelled` with `cause` set to `signal.reason`. */
  signal?: AbortSignal
}

export interface QueryResult {
  columns: Array<string>
  /** One object per row, keyed by column name. */
  rows: Array<Record<string, KgValue>>
  /** Present for statements that write. */
  stats?: MutationStats
  /** Advisory warnings for this query; never printed. */
  warnings: Array<string>
  /** Present only when `rowLimit` dropped rows. */
  truncated?: Truncated
}

export interface StreamOptions {
  /** Deadline in milliseconds for the query; `0` disables it. */
  timeoutMs?: number
  /** Cap on rows streamed; the query's own `LIMIT` still applies first. */
  rowLimit?: number
  /** Work budget (not a row cap); exceeding it fails the query. */
  maxWorkUnits?: number
  /**
   * Rows delivered per event-loop turn (default 1000, minimum 1). Between
   * batches the loop runs timers and I/O.
   */
  batchSize?: number
  /** Cancels the query and fails the pending `next()` when aborted: rejects `Cancelled` with `cause` set to `signal.reason`. */
  signal?: AbortSignal
}

export interface Truncated {
  rowLimit: number
  totalRows: number
}

/** Engine version, equal to the workspace package version. */
export declare function version(): string
